name: Main workflow

on: [pull_request, push]

jobs:
  style:
    strategy:
      fail-fast: false
      matrix: { job: [os: ubuntu-latest] }

    runs-on: ${{ matrix.job.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install npm packages
        run: yarn --frozen-lockfile

      - name: Check formatting
        run: yarn fmt:check

      - name: Ensure lib directory is up-to-date
        shell: bash
        run: |
          yarn build
          if [ "$(git status --porcelain | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes after build. See status below:"
            git diff
            exit 1
          fi

  build:
    strategy:
      fail-fast: false
      matrix:
        job:
          - { os: macos-10.15, ocaml-version: 4.05.0 }
          - { os: macos-10.15, ocaml-version: 4.08.1 }
          - { os: macos-10.15, ocaml-version: "4.10.1+flambda" }
          - { os: ubuntu-18.04, ocaml-version: 4.05.0 }
          - { os: ubuntu-18.04, ocaml-version: "4.07.1+musl+flambda" }
          - { os: ubuntu-18.04, ocaml-version: 4.08.1 }
          - { os: ubuntu-18.04, ocaml-version: "4.08.1+flambda" }
          - { os: ubuntu-18.04, ocaml-version: "4.08.1+fp+flambda" }
          - { os: ubuntu-18.04, ocaml-version: "4.08.1+musl+flambda" }
          - { os: ubuntu-18.04, ocaml-version: "4.10.1+musl+flambda" }
          - { os: ubuntu-20.04, ocaml-version: 4.05.0 }
          - { os: ubuntu-20.04, ocaml-version: "4.07.1+musl+flambda" }
          - { os: ubuntu-20.04, ocaml-version: 4.08.1 }
          - { os: ubuntu-20.04, ocaml-version: "4.08.1+musl+flambda" }
          - { os: ubuntu-20.04, ocaml-version: "4.10.0+32bit" }
          - { os: ubuntu-20.04, ocaml-version: "4.10.1+fp+flambda" }
          - { os: ubuntu-20.04, ocaml-version: "4.10.1+musl+flambda" }
          - { os: ubuntu-20.04, ocaml-version: "4.10.1+musl+static+flambda" }
          - { os: windows-2019, ocaml-version: 4.05.0 }
          - { os: windows-2019, ocaml-version: 4.08.1 }
          - { os: windows-2019, ocaml-version: "4.08.1+mingw32c" }
          - { os: windows-2019, ocaml-version: "4.10.1+mingw32c" }
          - { os: windows-2019, ocaml-version: "4.10.1+mingw64c" }
          - { os: windows-2019, ocaml-version: "4.10.1+msvc32c" }
          - { os: windows-2019, ocaml-version: "4.10.1+msvc64c" }

    runs-on: ${{ matrix.job.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Initialize workflow variables
        id: vars
        shell: bash
        run: |
          outputs() { for var in "$@" ; do echo steps.vars.outputs.${var}="${!var}"; echo ::set-output name=${var}::${!var}; done; }
          MINGW_ARCH='x86_64'; case '${{ matrix.job.ocaml-version }}' in *+mingw32*) MINGW_ARCH='i686' ;; *+mingw64*) MINGW_ARCH='x86_64' ;; esac
          MSVC_ARCH=''; case '${{ matrix.job.ocaml-version }}' in *+msvc32*) MSVC_ARCH='x86' ;; *+msvc64*) MSVC_ARCH='x64' ;; esac
          outputs MINGW_ARCH MSVC_ARCH

      - name: Use OCaml ${{ matrix.job.ocaml-version }}
        uses: ./
        with:
          ocaml-version: ${{ matrix.job.ocaml-version }}

      - name: Enable/config MSVC environment (if/when needed)
        uses: ilammy/msvc-dev-cmd@v1.3.0
        with:
          arch: "${{ steps.vars.outputs.MSVC_ARCH }}"
        if: contains(matrix.job.ocaml-version, '+msvc')

      - run: opam depext atd --install --verbose --yes
      - run: opam depext dune --install --verbose --yes
      - run: opam depext lwt --install --verbose --yes

      - run: opam depext yaml --install --verbose --yes
        ## [2020-09] non-working/unavailable for MSVC OCaml variants
        if: ${{ !contains(matrix.job.ocaml-version, '+msvc') }}

      - name: (lablgtk) extra 'MacOS' setup ${{ matrix.ocaml-version }}
        if: runner.os == 'macOS'
        shell:
          bash --norc --noprofile -e -o pipefail -c "dos2unix '{0}' 2>/dev/null
          ; source '{0}' ;"
        run: |
          brew install gtk+
      - name: (lablgtk) extra 'Linux' setup ${{ matrix.ocaml-version }}
        if: runner.os == 'Linux'
        shell:
          bash --norc --noprofile -e -o pipefail -c "dos2unix '{0}' 2>/dev/null
          ; source '{0}' ;"
        run: |
          sudo apt-get install -qq -yy libexpat1-dev libgtk2.0-dev
      - name:
          (lablgtk) extra 'Windows [non-MSVC]' setup ${{ matrix.ocaml-version }}
        if:
          (runner.os == 'Windows' && !contains(matrix.job.ocaml-version,
          '+msvc'))
        shell:
          bash --login --norc --noprofile -e -o pipefail -c "dos2unix '{0}'
          2>/dev/null ; source '{0}' ;"
        run: |
          # ref: <https://www.reddit.com/r/ocaml/comments/5rt3gh/installing_lablgtk_on_windows> @@ <https://archive.is/6GSXF>
          # * `cygwin-dl` and `cygwin-install` are from the 'depext-cygwinports' opam package (<https://github.com/fdopen/depext-cygwinports>)
          eval "$(opam env)"
          cygwin-dl --wait --quiet-mode --no-admin --no-desktop --packages mingw64-${{ steps.vars.outputs.MINGW_ARCH }}-glib2.0,mingw64-${{ steps.vars.outputs.MINGW_ARCH }}-gtk2.0,mingw64-${{ steps.vars.outputs.MINGW_ARCH }}-pango1.0,libgtk2.0_0,libgtk2.0_devel
      - name: lablgtk install
        ## [2020-09] non-working/unavailable for MSVC or musl OCaml variants
        ## [2020-09] non-working for 32bit variant (see [GH:garrigue/lablgtk#64](https://github.com/garrigue/lablgtk/issues/64))
        if:
          ${{ !( contains(matrix.job.ocaml-version, '+msvc') ||
          contains(matrix.job.ocaml-version, '+musl') ||
          contains(matrix.job.ocaml-version, '+32bit') ) }}
        shell:
          bash --login --norc --noprofile -e -o pipefail -c "dos2unix '{0}'
          2>/dev/null ; source '{0}' ;"
        run: |
          ocaml-env-exec () { ocaml-env >/dev/null 2>&1 && ocaml-env exec -- $* || $* ; } ## `ocaml-env` is not available for all ocaml switches
          eval "$(opam env)"
          ocaml-env-exec opam depext --install --verbose --yes lablgtk
