name: Main workflow

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - "**.md"
  push:
    branches:
      - master
    paths-ignore:
      - "**.md"

jobs:
  style:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install npm packages
        run: yarn --frozen-lockfile

      - name: Check formatting
        run: yarn fmt:check

      - name: Ensure lib directory is up-to-date
        shell: bash
        run: |
          yarn build
          if [ "$(git status --porcelain | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes after build. See status below:"
            git diff
            exit 1
          fi

  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-10.15
          # - ubuntu-16.04
          - ubuntu-18.04
          - ubuntu-20.04
          - windows-2019
        ocaml-version:
          - 4.08.1
          - 4.05.0

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: ./
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

      - run: opam depext yaml --install --verbose --yes
